# Generated by Django 4.2.7 on 2023-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
